In [1]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from loading import load_data, load_test
from preprocessing import preprocess
from preprocessing import preprocess_y

In [2]:
#variable name convention: data = train + validation
data_x_orig, data_y_orig = load_data() # loads from ".\data" by default
test_x_orig = load_test() #this is for submission purposes

In [3]:
data_x = preprocess(data_x_orig)
data_x

min_time_two_events  mean_time_two_events  10_p_time_two_events  \
Index                                                                     
1                  0.000000           5117.830300              0.000000   
2                  0.000000           1846.968401              0.000074   
3                  0.000000            686.300630              0.000071   
4                  0.000000           2174.335265              0.000000   
5                  0.000000            944.008551              0.000071   
6                  0.000000              0.943412              0.000000   
7                  0.000000            380.267415              0.000000   
8                  0.000000            580.891842              0.000000   
9                  0.000000           1932.224487              0.000000   
10                 0.000000           5834.927530              0.000000   
11                 0.000000            469.756424              0.000059   
12                 0.000000           3299.085879              0.000000   
13                 0.000000           1279.862582              0.000057   
14                 0.000000            119.294130              0.000000   
15                 0.000000           1047.555179              0.000278   
16                 0.000107             63.196574              0.000107   
17                 0.000000           6357.717988              0.000000   
18                 0.000000            122.295259              0.000000   
19                 0.000000           4413.754148              0.000074   
20                 0.000000           1632.802798              0.000000   
21                 0.000000           2276.061810              0.000000   
22                 0.000000            101.493969              0.000000   
23                 0.000000           1156.165686              0.000000   
24                 0.000000           1494.396289              0.000057   
25                 0.000053            329.650964              0.000053   
26                 0.000000            711.539694              0.000068   
27                 0.000000            496.892423              0.000126   
28                 0.000000            293.149477              0.000000   
29                 0.000000           1138.716047              0.000000   
30                 0.000000           1223.304326              0.000000   
...                     ...                   ...                   ...   
105753          4911.428700          12929.666504           4911.428700   
105754             0.000000             38.298472              0.000040   
105755             0.000000             23.543126              0.000059   
105756             0.000000            192.422000              0.000000   
105757             0.000000              7.960858              0.000000   
105758             0.000000             21.838050              0.000000   
105759             0.000029             38.017376              0.000052   
105760             0.000000            150.375761              0.000000   
105761             0.000000            309.368505              0.000000   
105762             0.000000            681.155480              0.000000   
105763             0.000000            323.151179              0.000171   
105764             0.000000             66.687001              0.000000   
105765             0.000000            232.436741              0.000037   
105766             0.000000            128.132179              0.000080   
105767             0.000000             81.416173              0.000000   
105768             0.000000            276.464861              0.000000   
105769             0.000000            105.828203              0.000021   
105770             0.000000             81.089528              0.000000   
105771             0.000000           1082.673096              0.000000   
105772             0.000000             59.440891              0.000000   
105773             0.000000      

In [4]:
data_y = preprocess_y(data_x_orig,data_y_orig)
data_y

HFT
Index          
1       NON HFT
2       NON HFT
3       NON HFT
4       NON HFT
5       NON HFT
6       NON HFT
7       NON HFT
8       NON HFT
9       NON HFT
10      NON HFT
11      NON HFT
12      NON HFT
13      NON HFT
14      NON HFT
15      NON HFT
16      NON HFT
17      NON HFT
18      NON HFT
19      NON HFT
20      NON HFT
21      NON HFT
22      NON HFT
23      NON HFT
24      NON HFT
25      NON HFT
26      NON HFT
27      NON HFT
28      NON HFT
29      NON HFT
30      NON HFT
...         ...
105753  NON HFT
105754  NON HFT
105755  NON HFT
105756  NON HFT
105757  NON HFT
105758  NON HFT
105759  NON HFT
105760  NON HFT
105761  NON HFT
105762  NON HFT
105763  NON HFT
105764  NON HFT
105765  NON HFT
105766  NON HFT
105767  NON HFT
105768  NON HFT
105769  NON HFT
105770  NON HFT
105771  NON HFT
105772  NON HFT
105773  NON HFT
105774  NON HFT
105775  NON HFT
105776  NON HFT
105777  NON HFT
105778  NON HFT
105779  NON HFT
105780  NON HFT
105781  NON HFT
105782  NON HFT

[105782 rows x 1 columns]

In [5]:
# look at missing data
s = data_x.isna().sum()/data_x.count()
s[data_x.isna().any()].sort_values(ascending=False)

Series([], dtype: float64)

In [7]:
# TODO use this to group traders together during cross-validation
from sklearn.model_selection import GroupKFold

X = [0.1, 0.2, 2.2, 2.4, 2.3, 4.55, 5.8, 8.8, 9, 10]
y = ["a", "b", "b", "b", "c", "c", "c", "d", "d", "d"]
groups = [1, 1, 1, 2, 2, 2, 3, 3, 3, 3]

gkf = GroupKFold(n_splits=3)
for train, test in gkf.split(X, y, groups=groups):
    print("%s %s" % (train, test))


[0 1 2 3 4 5] [6 7 8 9]
[0 1 2 6 7 8 9] [3 4 5]
[3 4 5 6 7 8 9] [0 1 2]
